/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * AceClub API
 * The backend API for AceClub Manager
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PostApiUsersCreateUserBody,
  User
} from '../models';

import { customInstance } from '../../lib/orvalMutator';




/**
 * @summary Get all users
 */
export type getApiUsersGetAllUsersResponse200 = {
  data: User[]
  status: 200
}

export type getApiUsersGetAllUsersResponseSuccess = (getApiUsersGetAllUsersResponse200) & {
  headers: Headers;
};
;

export type getApiUsersGetAllUsersResponse = (getApiUsersGetAllUsersResponseSuccess)

export const getGetApiUsersGetAllUsersUrl = () => {




  return `/api/users/GetAllUsers`
}

export const getApiUsersGetAllUsers = async ( options?: RequestInit): Promise<getApiUsersGetAllUsersResponse> => {

  return customInstance<getApiUsersGetAllUsersResponse>(getGetApiUsersGetAllUsersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiUsersGetAllUsersQueryKey = () => {
    return [
    `/api/users/GetAllUsers`
    ] as const;
    }


export const getGetApiUsersGetAllUsersQueryOptions = <TData = Awaited<ReturnType<typeof getApiUsersGetAllUsers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersGetAllUsers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiUsersGetAllUsersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsersGetAllUsers>>> = ({ signal }) => getApiUsersGetAllUsers({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUsersGetAllUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiUsersGetAllUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsersGetAllUsers>>>
export type GetApiUsersGetAllUsersQueryError = unknown


export function useGetApiUsersGetAllUsers<TData = Awaited<ReturnType<typeof getApiUsersGetAllUsers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersGetAllUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsersGetAllUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiUsersGetAllUsers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsersGetAllUsers<TData = Awaited<ReturnType<typeof getApiUsersGetAllUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersGetAllUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsersGetAllUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiUsersGetAllUsers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsersGetAllUsers<TData = Awaited<ReturnType<typeof getApiUsersGetAllUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersGetAllUsers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all users
 */

export function useGetApiUsersGetAllUsers<TData = Awaited<ReturnType<typeof getApiUsersGetAllUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersGetAllUsers>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUsersGetAllUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create user
 */
export type postApiUsersCreateUserResponse201 = {
  data: User
  status: 201
}

export type postApiUsersCreateUserResponseSuccess = (postApiUsersCreateUserResponse201) & {
  headers: Headers;
};
;

export type postApiUsersCreateUserResponse = (postApiUsersCreateUserResponseSuccess)

export const getPostApiUsersCreateUserUrl = () => {




  return `/api/users/CreateUser`
}

export const postApiUsersCreateUser = async (postApiUsersCreateUserBody: PostApiUsersCreateUserBody, options?: RequestInit): Promise<postApiUsersCreateUserResponse> => {

  return customInstance<postApiUsersCreateUserResponse>(getPostApiUsersCreateUserUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiUsersCreateUserBody,)
  }
);}




export const getPostApiUsersCreateUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsersCreateUser>>, TError,{data: PostApiUsersCreateUserBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiUsersCreateUser>>, TError,{data: PostApiUsersCreateUserBody}, TContext> => {

const mutationKey = ['postApiUsersCreateUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiUsersCreateUser>>, {data: PostApiUsersCreateUserBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiUsersCreateUser(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiUsersCreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUsersCreateUser>>>
    export type PostApiUsersCreateUserMutationBody = PostApiUsersCreateUserBody
    export type PostApiUsersCreateUserMutationError = unknown

    /**
 * @summary Create user
 */
export const usePostApiUsersCreateUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsersCreateUser>>, TError,{data: PostApiUsersCreateUserBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiUsersCreateUser>>,
        TError,
        {data: PostApiUsersCreateUserBody},
        TContext
      > => {
      return useMutation(getPostApiUsersCreateUserMutationOptions(options), queryClient);
    }
