/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * AceClub API
 * The backend API for AceClub Manager
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  LoginResponseSchema,
  PostApiAuthLoginBody,
  PutApiAuthRegisterBody
} from '../models';

import { customInstance } from '../../lib/orvalMutator';




export type postApiAuthLoginResponse200 = {
  data: LoginResponseSchema
  status: 200
}

export type postApiAuthLoginResponse401 = {
  data: void
  status: 401
}

export type postApiAuthLoginResponseSuccess = (postApiAuthLoginResponse200) & {
  headers: Headers;
};
export type postApiAuthLoginResponseError = (postApiAuthLoginResponse401) & {
  headers: Headers;
};

export type postApiAuthLoginResponse = (postApiAuthLoginResponseSuccess | postApiAuthLoginResponseError)

export const getPostApiAuthLoginUrl = () => {




  return `/api/auth/Login`
}

export const postApiAuthLogin = async (postApiAuthLoginBody: PostApiAuthLoginBody, options?: RequestInit): Promise<postApiAuthLoginResponse> => {

  return customInstance<postApiAuthLoginResponse>(getPostApiAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiAuthLoginBody,)
  }
);}




export const getPostApiAuthLoginMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: PostApiAuthLoginBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: PostApiAuthLoginBody}, TContext> => {

const mutationKey = ['postApiAuthLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthLogin>>, {data: PostApiAuthLoginBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthLogin(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogin>>>
    export type PostApiAuthLoginMutationBody = PostApiAuthLoginBody
    export type PostApiAuthLoginMutationError = void

    export const usePostApiAuthLogin = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: PostApiAuthLoginBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthLogin>>,
        TError,
        {data: PostApiAuthLoginBody},
        TContext
      > => {
      return useMutation(getPostApiAuthLoginMutationOptions(options), queryClient);
    }
    export type putApiAuthRegisterResponse201 = {
  data: LoginResponseSchema
  status: 201
}

export type putApiAuthRegisterResponseSuccess = (putApiAuthRegisterResponse201) & {
  headers: Headers;
};
;

export type putApiAuthRegisterResponse = (putApiAuthRegisterResponseSuccess)

export const getPutApiAuthRegisterUrl = () => {




  return `/api/auth/Register`
}

export const putApiAuthRegister = async (putApiAuthRegisterBody: PutApiAuthRegisterBody, options?: RequestInit): Promise<putApiAuthRegisterResponse> => {

  return customInstance<putApiAuthRegisterResponse>(getPutApiAuthRegisterUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putApiAuthRegisterBody,)
  }
);}




export const getPutApiAuthRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAuthRegister>>, TError,{data: PutApiAuthRegisterBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putApiAuthRegister>>, TError,{data: PutApiAuthRegisterBody}, TContext> => {

const mutationKey = ['putApiAuthRegister'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiAuthRegister>>, {data: PutApiAuthRegisterBody}> = (props) => {
          const {data} = props ?? {};

          return  putApiAuthRegister(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof putApiAuthRegister>>>
    export type PutApiAuthRegisterMutationBody = PutApiAuthRegisterBody
    export type PutApiAuthRegisterMutationError = unknown

    export const usePutApiAuthRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAuthRegister>>, TError,{data: PutApiAuthRegisterBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiAuthRegister>>,
        TError,
        {data: PutApiAuthRegisterBody},
        TContext
      > => {
      return useMutation(getPutApiAuthRegisterMutationOptions(options), queryClient);
    }
