/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * AceClub API
 * The backend API for AceClub Manager
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiUsersCreateUserBodyRole } from './postApiUsersCreateUserBodyRole';

export type PostApiUsersCreateUserBody = {
  /** @minLength 2 */
  fullName: string;
  email: string;
  phone?: string;
  role: PostApiUsersCreateUserBodyRole;
  /** @minimum 0 */
  makeupCredits?: number;
  /** @minLength 8 */
  password: string;
};
