/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * AceClub API
 * The backend API for AceClub Manager
 * OpenAPI spec version: 1.0.0
 */

export type PostApiUsersCreateUserBodyRole = typeof PostApiUsersCreateUserBodyRole[keyof typeof PostApiUsersCreateUserBodyRole];


export const PostApiUsersCreateUserBodyRole = {
  ADMIN: 'ADMIN',
  COACH: 'COACH',
  TRAINEE: 'TRAINEE',
} as const;
