/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * AceClub API
 * The backend API for AceClub Manager
 * OpenAPI spec version: 1.0.0
 */

import { customInstance } from '../lib/orvalMutator';
import type { User, CreateUserRequest, LoginResponse, LoginRequest, AuthenticatedUser, Court, GetApiRolesGetAllRoles200 } from './models';

export const api = {
  users: {
    getAllUsers: () => customInstance<User[]>({url: `/api/users/GetAllUsers`, method: 'GET' }),
    createUser: (createUserRequest: CreateUserRequest) => customInstance<User>({url: `/api/users/CreateUser`, method: 'POST', headers: {'Content-Type': 'application/json', }, data: createUserRequest }),
  },
  auth: {
    login: (loginRequest: LoginRequest) => customInstance<LoginResponse>({url: `/api/auth/Login`, method: 'POST', headers: {'Content-Type': 'application/json', }, data: loginRequest }),
    register: (createUserRequest: CreateUserRequest) => customInstance<LoginResponse>({url: `/api/auth/Register`, method: 'PUT', headers: {'Content-Type': 'application/json', }, data: createUserRequest }),
    getAuthUser: () => customInstance<AuthenticatedUser>({url: `/api/auth/getAuthUser`, method: 'GET' }),
  },
  roles: {
    getAllRoles: () => customInstance<GetApiRolesGetAllRoles200>({url: `/api/roles/GetAllRoles`, method: 'GET' }),
  },
  courts: {
    getAllCourts: () => customInstance<Court[]>({url: `/api/courts/GetAllCourts`, method: 'GET' }),
    createCourt: () => customInstance<Court>({url: `/api/courts/CreateCourt`, method: 'POST' }),
  },
};
