/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * AceClub API
 * The backend API for AceClub Manager
 * OpenAPI spec version: 1.0.0
 */

import { customInstance } from '../lib/orvalMutator';
import type { User, CreateUserRequest, LoginResponse, LoginRequest } from './models';

export const api = {
  users: {
    getAllUsers: () => customInstance<User[]>({url: `/api/users/GetAllUsers`, method: 'GET' }),
    createUser: (createUserRequest: CreateUserRequest) => customInstance<User>({url: `/api/users/CreateUser`, method: 'POST', headers: {'Content-Type': 'application/json', }, data: createUserRequest }),
  },
  auth: {
    login: (loginRequest: LoginRequest) => customInstance<LoginResponse>({url: `/api/auth/Login`, method: 'POST', headers: {'Content-Type': 'application/json', }, data: loginRequest }),
    register: (createUserRequest: CreateUserRequest) => customInstance<LoginResponse>({url: `/api/auth/Register`, method: 'PUT', headers: {'Content-Type': 'application/json', }, data: createUserRequest }),
  },
};
