/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * AceClub API
 * The backend API for AceClub Manager
 * OpenAPI spec version: 1.0.0
 */

export type UserRole = typeof UserRole[keyof typeof UserRole];

export const UserRole = {
  ADMIN: 'ADMIN',
  COACH: 'COACH',
  TRAINEE: 'TRAINEE',
} as const;

export type UserGender = typeof UserGender[keyof typeof UserGender];

export const UserGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;

export interface User {
  id: string;
  /** @minLength 2 */
  fullName: string;
  email: string;
  phone: string;
  role: UserRole;
  /** @minimum 0 */
  makeupCredits?: number;
  createdAt: string;
  /**
     * @minLength 8
     * @nullable
     */
  password: string | null;
  birthDate: string;
  gender: UserGender;
  /** @nullable */
  address: string | null;
  /** @nullable */
  membershipStartDate: string | null;
  /** @nullable */
  membershipEndDate: string | null;
}

export type CreateUserRequestRole = typeof CreateUserRequestRole[keyof typeof CreateUserRequestRole];

export const CreateUserRequestRole = {
  ADMIN: 'ADMIN',
  COACH: 'COACH',
  TRAINEE: 'TRAINEE',
} as const;

export type CreateUserRequestGender = typeof CreateUserRequestGender[keyof typeof CreateUserRequestGender];

export const CreateUserRequestGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;

export interface CreateUserRequest {
  /** @minLength 2 */
  fullName: string;
  email: string;
  phone: string;
  role: CreateUserRequestRole;
  /**
     * @minLength 8
     * @nullable
     */
  password: string | null;
  birthDate: string;
  gender: CreateUserRequestGender;
  /** @nullable */
  address: string | null;
  /** @nullable */
  membershipStartDate: string | null;
  /** @nullable */
  membershipEndDate: string | null;
}

export interface LoginResponse {
  user: User;
  token: string;
}

export interface LoginRequest {
  email: string;
  /** @minLength 6 */
  password: string;
}

export interface AuthenticatedUser {
  user: User;
  sub: string;
  permissions: string[];
}

export type CourtSurface = typeof CourtSurface[keyof typeof CourtSurface];

export const CourtSurface = {
  TENNIS_HARD: 'TENNIS_HARD',
  PADEL: 'PADEL',
  PICKELBALL: 'PICKELBALL',
} as const;

export interface Court {
  id: string;
  name: string;
  /** @nullable */
  location: string | null;
  surface: CourtSurface;
  isActive: boolean;
  createdAt: string;
}

export type GetApiRolesGetAllRoles200 = { [key: string]: unknown };
