/**
 * Generated by orval v8.8.0 🍺
 * Do not edit manually.
 * AceClub API
 * The backend API for AceClub Manager
 * OpenAPI spec version: 1.0.0
 */
import type { LoginResponseSchemaRole } from './loginResponseSchemaRole';

export interface LoginResponseSchema {
  id: string;
  /** @minLength 2 */
  fullName: string;
  email: string;
  phone?: string;
  role: LoginResponseSchemaRole;
  /** @minimum 0 */
  makeupCredits?: number;
  createdAt: string;
  token: string;
}
